//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSide.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        public int idUsuario { get; set; }
        public string usuario { get; set; }
        public string pass { get; set; }
        public string nombreUsuario { get; set; }
        public string apellidoUsuario { get; set; }
        public int docuUsuario { get; set; }
        public int rolUsuario { get; set; }
    
        public virtual rolUsuarios rolUsuarios { get; set; }
    }
}
